-------------------------------------- (1). TOTAL AND AVERAGE SALES OVERALL.

							SELECT * FROM WALLMART_2

							SELECT SUM(WEEKLY_SALES) AS 'TOTAL_WEEKLY_SALES', AVG(WEEKLY_SALES) AS 'AVG_WEEKLY_SALES'
							FROM WALLMART_2



-------------------------------------- (2). SALES TRENDS BY MONTH OR YEAR.

							SELECT YEAR, SUM(WEEKLY_SALES) AS 'TOT_WEEKLY_SALES'
							FROM WALLMART_2
							GROUP BY YEAR


-------------------------------------- (3). SALES COMPARISON: HOLIDAY WEEKS VS. NON-HOLIDAY WEEKS.
							
							SELECT HOLIDAY_FLAG, SUM(WEEKLY_SALES) AS 'TOTAL_SALES', AVG(WEEKLY_SALES) AS 'AVG_SALES', 
							COUNT(*) AS 'NO_OF_WEEKS'
							FROM WALLMART_2
							GROUP BY HOLIDAY_FLAG

							
-------------------------------------- (4). STORE-LEVEL PERFORMANCE METRICS.
							SELECT * FROM WALLMART_2

							-- PERFORMANCE VALUE = (AVG_SALES * AVG_CPI)/(AVG_FUEL_PRICE * AVG_UNEMPLOYMENT)

							SELECT STORE, SUM(WEEKLY_SALES) AS 'TOT_SALES', AVG(WEEKLY_SALES) AS 'AVG_SALES', 
											 
											 AVG(CPI) AS 'AVG_CPI', AVG(FUEL_PRICE) AS 'AVG_FUEL_PRICE',
											 AVG(UNEMPLOYMENT) AS 'AVG_UNEMPLOYMENT', 
											 (AVG(CPI)*AVG(WEEKLY_SALES))/(AVG(FUEL_PRICE)*AVG(UNEMPLOYMENT)*1000000) AS 'PERFORMANCE_VALUE'
							FROM WALLMART_2
							GROUP BY STORE
							ORDER BY PERFORMANCE_VALUE DESC

							

-------------------------------------- (5). IDENTIFY ANY CORRELATION BETWEEN SALES AND CPI/FUEL/UNEMPLOYMENT.
							
							SELECT * FROM WALLMART_2 
											
-----------------------------------------------  CORRELATION BETWEEN SALES AND CPI
							SELECT STORE, AVG(WEEKLY_SALES) AS 'AVG_SALES', AVG(CPI) AS 'AVG_CPI'
							FROM WALLMART_2
							GROUP BY STORE
							ORDER BY AVG_SALES DESC 
							-- NO CORRELATION

-----------------------------------------------  CORRELATION BETWEEN SALES AND FUEL_PRICE
							SELECT STORE, AVG(WEEKLY_SALES) AS 'AVG_SALES', AVG(FUEL_PRICE) AS 'AVG_FUEL_PRICE'
							FROM WALLMART_2
							GROUP BY STORE
							ORDER BY AVG_SALES DESC
							-- NO CORRELATION
							
-----------------------------------------------  CORRELATION BETWEEN SALES AND UNEMPLOYMENT
							SELECT STORE, AVG(WEEKLY_SALES) AS 'AVG_SALES', AVG(UNEMPLOYMENT) AS 'AVG_UNEMPLOYMENT'
							FROM WALLMART_2
							GROUP BY STORE
							ORDER BY AVG_SALES DESC
							-- NO CORRELATION
